### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by kmgallahan**
#### Description

- Fix minor markdown and spelling issues
- Add a TOC
- Remove link to unavailable UserVoice instance

### CODE REVIEW

**Review by ltrzesniewski — COMMENTED** [review]
Thanks!

Though I don't think adding a TOC is necessary since GitHub already generates one automatically:

image

**Comment by kmgallahan** [comment]
I'm torn on embedded TOCs vs. that drop down. The latter requires no setup and maintenance, but it only shows a small number of topics without scrolling and the width often causes lines to get wrapped.

Your call though - 👍  👎

**Comment by ltrzesniewski** [comment]
Well, I'd rather not add a TOC as it would have to be maintained, and probably also added to all of the other Fody addins for consistency. That seems like a lot of work for little benefit.

But since you insist, let's leave the decision to @SimonCropp.

**Comment by tom-englert** [comment]
I don't see a real benefit in a TOC

**Review by ltrzesniewski — APPROVED** [review]

**Comment by ltrzesniewski** [comment]
Thanks!

**Pull request merged**
