### PR TITLE
Switch Anotar.Custom to .NET Standard completely

### PR DESCRIPTION
**Pull request by tpluscode**
This PR aims to migrate Anotar.Custom completely to new dotnet tooling:

* All `Custom*` projects now using new `csproj` format
* Last time I checked NUnit only worked with project.json so I switched to XUnit
* On top of that I made all tests parametrized so that muliple builds are weaved and tested (Core, net35, etc)

There is an issue though. The weaver fails to process a `netcoreapp1.1` build. Whenever it gets to `ModuleWeaver#LoadSystemTypes`, it fails on the line 

``` c#
var stringType = ModuleDefinition.TypeSystem.String.Resolve();
```

it then breaks because `Resolve` returns null. What can I do about that?

~Finally, is there no AppVeyor set up for Anotar?~

Okay, I see it is but without appveyor.yaml. Do you only rely on configuration on ci.appveyor.com?

### CODE REVIEW

**Comment by tpluscode** [comment]
So, it seems that PepitaPackage doesn't work with `dotnet` (or does it?). Fortunately it wasn't all that hard to reconfigure the project to use the existing setup almost intact. I added a separate sln temporarily for simplicity until all Anotar.* packages are migrated. I build and pack by running

```
dotnet pack Anotar.NetStandard.sln -c Release /p:Version=4.0.0 -o ..\NuGetBuild
```

Works almost the same as before. The difference is that all built packages will be in the `NuGetBuild` folder directly.

**Comment by tpluscode** [comment]
Please help me out with your AppVeyor settings. Maybe you could commit the CI configuration file into `master`?

Converting all loggers to new csproj will tak some effort because not all of them support the same .NET Standard/Core, if at all. But anyway, moving everything to new format will simplify build (compared to having both `dotnet build` and old msbuild). 

I can proceed with that if you'd approve of my removing pepita and the direction in general.

**Comment by SimonCropp** [comment]
want to be a project maintainer?

**Comment by tpluscode** [comment]
Sure, I'll be glad to help

**Comment by tpluscode** [comment]
@SimonCropp could you add me as owner to Anotar NuGet package?

**Pull request merged**
