### PR TITLE
Updated Anotar.CommonLogging.Fody to use Common.Logging 3.0.0.

### PR DESCRIPTION
**Pull request by TimMurphy**
- Updated Common.Logging NuGet package to 3.0.0.
- Updated Anotor.CommonLogging.nuspec's Common.Logging dependency to 3.0.0.
- Fixed code to handle ILog moving from Common.Logging to Common.Logging.Core.

### CODE REVIEW

**Comment by SimonCropp** [comment]
Do u need to rebase?

**Comment by TimMurphy** [comment]
Silly me assumed a new fork had been created. I have to leave shortly. I'll advise when rebase is complete.

**Comment by SimonCropp** [comment]
Cool. Let me know and I will merge and release

**Comment by TimMurphy** [comment]
OK. I think everything is right to go. Please bear the following in mind.

- This is the first time I've update a fork from upstream repo.
- First time I've rebased a feature branch with master.
- packages.config in CommonLogging had merge conflicts but I reasonably confidently I resolved those correctly.
- The last commit was forced.

All that said I reasonably confident its OK:

- GitHub now reports this pull request can be automatically merged by project collaborators.
- All unit tests pass.
- I've successfully added the [MyGet](https://www.myget.org/feed/timpmurphy/package/Anotar.CommonLogging.Fody) version of the package to a project.

**Comment by SimonCropp** [comment]
thanks. this is on nuget

**Pull request merged**
