### PR TITLE
Fixed SystemTypesResolver for .NET Standard & .NET 3.5

### PR DESCRIPTION
**Pull request by mstyura**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@tpluscode LGTM. Any objections?

**Comment by tpluscode** [comment]
What do you think about adding some kind of integration test to the build where we'd use the `SolutionDir/Tools` convention to load the plugin and see whether `dotnet build` doesn't fail?

**Comment by tpluscode** [comment]
I don't think I'll have the time today but I'd get down to it tomorrow. Unless @mstyura has a minimal failing example and could attach to this PR or the linked issue?

**Comment by SimonCropp** [comment]
Good point @tpluscode

**Comment by tpluscode** [comment]
Oh shoot, it seem that running such integration test build on CI is currently blocked by Fody/Fody#330. I'll create a separate PR. This fix works as advertised so I'll merge now

**Pull request merged**
