### PR TITLE
Anotar.Serilog netcore migration

### LINKED ISSUE #101: .NET Standard Support- Serilog
Serilog has log supported even .NET Standard 1.0 so Anotar.Serilog is definitely possible :)

### PR DESCRIPTION
**Pull request by tpluscode**
Fixes #101

### CODE REVIEW

**Comment by NPSF3000** [comment]
How goes this?  We'd really appreciate support on .net core for serilog.

**Comment by tpluscode** [comment]
Good question. All tests pass but I don't remember why I didn't merge this already. If only my Visual Studio installation wasn't all messed up right now. How about I publish a prerelease and for Serilog and you could see if it works fine?

**Comment by NPSF3000** [comment]
Can't make any promises, but if a pre-release was around I should be able to sneak it into a project I'm working on.

**Comment by tpluscode** [comment]
Please try [https://www.nuget.org/packages/Anotar.Serilog.Fody/3.3.1-beta3](3.3.1-beta3)

**Comment by NPSF3000** [comment]
Just tried 3.3.2-beta-0001 and it seems to work.  Will let you know if any quirks appear.

Thanks!

**Pull request merged**
